String kAppName = 'Foody';
String kApiUrl = 'https://projectapi-khanhpham.herokuapp.com';
String kLoginUrl = '$kApiUrl/dang-nhap';
String kAllPostsUrl = '$kApiUrl/dia-diem';
String kSingUpUrl = '$kApiUrl/dang-ky';
String kAddPostUrl = '$kApiUrl/them-dia-diem';
String kPostCommentUrl = '$kApiUrl/binh-luan';
String kPromotionImagesUrl = '$kApiUrl/lay-khuyen-mai';
Map<String, String> kApiHeader = {"Content-Type" : "application/json"};
